{"name": "Успешный вход по ручке логина", "status": "passed", "description": "Проверяем попытку входа с отправкой существующих данных", "start": 1736846654534, "stop": 1736846654833, "uuid": "b2616203-7944-4419-845d-4dee4de46609", "historyId": "d0309d3f0e7911cef7e6fa887d1581d8", "testCaseId": "d0309d3f0e7911cef7e6fa887d1581d8", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "LAPTOP-B6TT34TV"}, {"name": "thread", "value": "17268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}